[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "moalmanac"
version = "0.9.0"
description = "Clinical interpretation algorithm for cancer genomics"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.14, <3.15"
dependencies = [
  "flask>=3.0",
  "Frozen-Flask>=1.0",
  "ipykernel>=6.29",
  "jupyter>=1.0",
  "matplotlib>=3.10",
  "numpy>=2.0",
  "pandas>=3.0",
  "requests>=2.32",
  "ruff>=0.15",
  "scikit-learn>=1.7",
  "scipy>=1.13",
]

[project.urls]
Repository = "https://github.com/vanallenlab/moalmanac"

[project.optional-dependencies]
dev = ["pip-tools"]

[tool.setuptools]
license-files = ["LICENSE*"]

[tool.setuptools.packages.find]
where = ["."]
include = ["moalmanac*"]

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
ignore = ["COM819"]
fixable = ["ALL"]
select = [
  "B",      # flake8-bugbear
  "COM",    # use trailing commas
  "COM812",
  "E",      # pycodestyle errors
  "F",      # pyflakes
  "I",      # isort
  "SIM",    # flake8-simplify
  "RUF",    # ruff-native rules
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
]

[tool.ruff.lint.isort]
force-single-line = true
split-on-trailing-comma = true
